config/routes.rb
Rails.application.routes.draw do
  root to: "top#top"
  devise_for :users
  get 'users/show'
  get 'users', to: 'top#user'
  get  "contacts/send_mail"  => "contacts#send_mail"
  get 'blogs/favorite', to: 'blogs#favorite'

  resources :blogs do
    resources :comments, only: [:create, :edit, :destroy]
  end
  resources :contacts
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def top
  end

  def user
    @users = User.all
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/top.html.erb
<h1>Top</h1>
<p id="notice"><%= notice %></p>
<%= link_to "ブログ一覧", blogs_path, class: 'btn btn-primary text-white' %>
<%= link_to "ユーザー一覧", users_path, class: 'btn btn-info text-white' %>
<%= link_to "お気に入り一覧", blogs_favorite_path, class: 'btn btn-warning text-white' %>

<h2>自己紹介</h2>
<h1>小川乃輝 (おがわ だいき)</h1>
<img src="4FBB3039-3A35-4AE1-A2E4-9CE09C9C7F5A_1_105_c.jpeg" alt="">
<div>
  <h2>現在の職業</h2>
  <ul>
    <li>武蔵大学 24卒 (現在休学中)</li>
    <li>42東京</li>
    <li>株式会社SUPER STUDIO(インターン)</li>
  </ul>
</div>

<div>
  <h2>所属チーム</h2>
  <p>未所属</p>
</div>

<div>
<h2>好きなこと</h2>
<ul>
    <li>サックス演奏(超初心者)</li>
    <li>ミュージカル鑑賞</li>
    <li>Apple製品</li>
    <li>コーディング</li>
    <li>美味しい食べ物(特にカレー)</li>
  </ul>
</div>

<div>
  <h2>SUPER STUDIOをどこで知ったのか</h2>
  <p>Wantedlyで声をかけていただいたのがきっかけ</p>
</div>

<div>
  <h2>なぜプログラミングをしようと思ったのか</h2>
  <p>大好きなMacが活躍できることをしたかった</p>
</div>

<div>
  <h2>プログラミングを通してどんなところを目指すのか</h2>
  <p>Value製造機になる</p>
</div>

<div>
  <h2>1年後の姿（1年後、自分はこうなっている！）</h2>
  <p>自分のサービスを運用している</p>
</div>

app/views/top/user.html.erb
<div class="container my-container">
  <h1>ユーザー一覧</h1>
  <div class="row">
    <% @users.each do |user| %>
      <div class="col-md-2" style="margin-top: 12px;">
        <h2><%= user.name %></h2>
        <%= link_to '詳細', users_show_path(id: user.id), class: 'btn btn-primary text-white' %>
      </div>
    <% end %>
  </div>
</div>