config/routes.rb
Rails.application.routes.draw do
  root to: "top#top"
  devise_for :users
  get 'users/show'
  get 'users', to: 'top#user'
  get  "contacts/send_mail"  => "contacts#send_mail"
  get 'blogs/favorite', to: 'blogs#favorite'

  resources :blogs do
    resources :comments, only: [:create, :edit, :destroy]
  end
  resources :contacts
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 10 }
  paginates_per 10
  scope :index_all, -> {
    select(:id, :user_id, :title, :content, :created_at) #フィールドごとにレコードを取得
    .order(created_at: :asc) #created_atカラムの昇順に並び替え
    .includes(:user) #ユーザを事前に取得してN+1防止
  }
  belongs_to :user
  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = @blogs = Blog.index_all.page(params[:page])
  end


  # GET /blogs/1 or /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
    @comments = @blog.comments
    @comment = @blog.comments.build
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  # GET /blogs/new
  def new
    if user_signed_in?
      @blog = Blog.new
    else
      redirect_to blogs_url, notice: "登録を完了させてください。"
    end
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      NoticeMailer.sendmail_blog(@blog).deliver #追記
      redirect_to @blog, notice: 'ブログが作成されました'
    else
      render :new
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog.id), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def favorite
    ＠blogs = current_user.favorite_blogs
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field m-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control'%>
  </div>

  <div class="field m-5">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<<div class="container my-container">
  <h2>編集画面</h2>
  <%= render 'form', blog: @blog %>
  <%= link_to 'ホーム', blogs_path, class: 'btn btn-secondary text-white' %>
</div>

app/views/blogs/favorite.html.erb
<h1>favarite</h1>
<div class="row">
  <%@blogs.each do |blog| %>
    <div class="col-md-4" style="margin-top: 12px;">
      <div class="box-in">
        <h2><%= blog.title %></h2>
        <p><%= blog.content %></p>
        <p><%= blog.created_at %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>
<div class="row">
  <%@blogs.each do |blog| %>
    <div class="col-md-4" style="margin-top: 12px;">
      <div class="box-in">
        <h2><%= blog.title %></h2>
        <p><%= blog.content %></p>
        <p><%= blog.created_at %></p>
        <div class="blog-links">
          <%= link_to '詳細', blog, class: 'btn btn-primary text-white' %>
          <%= link_to '編集', edit_blog_path(blog), class: 'btn btn-info text-white' %> |
          <%= link_to '削除', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger text-white' %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div id="new-blog-link" class="button">
  <%= link_to '新規作成', new_blog_path, class: 'btn btn-primary text-white' %>
</div>

app/views/blogs/new.html.erb
<div class="container my-container">
<h1>新規作成</h1>
    <%= render 'form', blog: @blog %>
    <%= link_to 'ホーム', blogs_path, class: 'btn btn-secondary text-white' %>
</div>

app/views/blogs/show.html.erb
<div class="container my-container">
  <h1>詳細</h1>
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Title:</strong>
    <%= @blog.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @blog.content %>
  </p>

  <% unless @blog.user == current_user %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id, id: @favorite), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-default' %>
    <% end %>
  <% end %>

  <div class="comment-wrapper border-top mb-10">
    <p class="mt-5">コメント一覧</p>
    <% @comments.each do |c| %>
      <div>
        <a href="<%= users_show_path(c.user_id) %>">icon</a>
        <br />
        <%= c.content %>
        <div class="blog-links">
          <%= link_to '編集', "#", class: 'btn btn-info text-white' %> |
          <%= link_to '削除', "#", method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger text-white' %>
        </div>
      </div>
      <br />
    <% end %>
    <% if user_signed_in? %>
      <%= form_with(model: [@blog, @comment], local: true) do |f| %>
        <%= f.text_area :content, class: "form-control", rows: 5 %>
        <%= button_tag type: "submit", class: "btn btn-success float-right mt-1" do %>
          <i class="far fa-comments"></i> コメントする
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>