config/routes.rb
Rails.application.routes.draw do
  root to: "top#top"
  devise_for :users
  get 'users/show'
  get 'users', to: 'top#user'
  get  "contacts/send_mail"  => "contacts#send_mail"
  get 'blogs/favorite', to: 'blogs#favorite'

  resources :blogs do
    resources :comments, only: [:create, :edit, :destroy]
  end
  resources :contacts
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ send_mail show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contact = Contact.new
    render :new
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    if params[:id].present?
      set_contact
    else
      @contact = Contact.new
    end
  end

  def send_mail
    NoticeMailer.sendmail_contact(@contact).deliver #追記
    redirect_to root_url, notice: "お問い合わせが完了しました！"
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to @contact
    else
      render :new
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :category, :content)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error")%> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container my-5">
    <form method="post" action="">
      <div class="form-group form-item">
        <%= form.label :名前 %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group form-item">
        <%= form.label :メールアドレス %>
        <%= form.text_field :email, class: "form-control" %>
      </div>
      <div class="field form-group form-item">
        <%= form.label :カテゴリー %>
        <ul class="list-unstyled">
          <li>
            <%= form.radio_button :category, 1 %>
            <%= form.label "Achieveに関して" %>
          </li>
          <li>
            <%= form.radio_button :category, 2 %>
            <%= form.label "テキストに関して" %>
          </li>
          <li>
            <%= form.radio_button :category, 3 %>
            <%= form.label "説明会に関して" %>
          </li>
          <li>
            <%= form.radio_button :category, 4 %>
            <%= form.label "その他" %>
          </li>
        </ul>
      </div>
      <div class="form-group form-item">
        <%= form.label :content %>
        <%= form.text_area :content, class: "form-control" %>
      </div>
      <div class="actions form-group form-item">
        <%= form.submit "内容確認" %>
      </div>
    </form>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="container my-container">
  <h1>Editing Contact</h1>
  <%= render 'form', contact: @contact %>
  <%= link_to 'Show', @contact %> |
  <%= link_to 'Back', contacts_path %>
</div>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Email</th>
      <th>Category</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.title %></td>
        <td><%= contact.email %></td>
        <td><%= contact.category %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>
<%= link_to 'Back', blogs_path %>

app/views/contacts/new.html.erb
<div class="container my-container">
<h1 class="title">New Contact</h1>
    <%= render 'form', contact: @contact %>
    <%= link_to 'ホーム', blogs_path, class: 'btn btn-secondary text-white' %>
</div>

app/views/contacts/show.html.erb
<div class="container my-container">
  <h1>内容確認</h1>
  <p>
    <strong>名前:</strong>
    <br>
    <%= @contact.name %>
  </p>

  <p>
    <strong>メールアドレス:</strong>
    <br>
    <%= @contact.email %>
  </p>

  <p>
    <strong>カテゴリー:</strong>
    <br>
    <%= ret_category(@contact.category) %>
  </p>

  <p>
    <strong>内容:</strong>
    <br>
    <%= @contact.content %>
  </p>

  <%= link_to '戻る', new_contact_path(id: @contact.id), class: 'btn btn-secondary' %>
  <%= link_to '送信', contacts_send_mail_path(id: @contact.id), class: 'btn btn-success' %>
  </div>